# Generated by Django 5.1.5 on 2025-02-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trade_date', models.DateTimeField()),
                ('execution_time', models.DateTimeField()),
                ('counterparty_1_name', models.CharField(max_length=255)),
                ('counterparty_1_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('counterparty_1_country', models.CharField(max_length=50)),
                ('counterparty_2_name', models.CharField(max_length=255)),
                ('counterparty_2_account_id', models.CharField(blank=True, max_length=50, null=True)),
                ('counterparty_2_country', models.CharField(max_length=50)),
                ('instrument_type', models.CharField(max_length=50)),
                ('instrument_symbol', models.CharField(max_length=50)),
                ('instrument_ISIN', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_currency', models.CharField(max_length=10)),
                ('notional_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('settlement_date', models.DateField()),
                ('settlement_currency', models.CharField(max_length=10)),
                ('settlement_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('settlement_bank_name', models.CharField(max_length=255)),
                ('settlement_account_number', models.CharField(max_length=50)),
                ('trade_reference_id', models.CharField(max_length=50)),
                ('source_system', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('buy_or_sell', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
