# Generated by Django 4.2.4 on 2025-02-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('trade_date', models.DateTimeField()),
                ('primary_asset_class', models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt')], max_length=20)),
                ('secondary_asset_class', models.CharField(choices=[('shares', 'Shares'), ('preffered_shares', 'Preffered Shares'), ('bonds', 'Bonds'), ('medium_term', 'Medium Term'), ('asset_backed_securities', 'Asset Backed Securities'), ('mortage_backed_securities', 'Mortage Backed Securities'), ('depository_receipts', 'Depository Receipts'), ('money_market_instrument', 'Money_Market_Instrument')], max_length=50)),
                ('isin', models.CharField(max_length=40)),
                ('buy_or_sell', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('instrument_name', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('counterparty_id', models.CharField(max_length=50)),
                ('counterparty_type', models.CharField(choices=[('individual', 'Individual'), ('institution', 'Institution')], max_length=20)),
                ('counterparty_risk_rating', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_volatility', models.DecimalField(decimal_places=2, max_digits=4)),
                ('market_liquidity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('trade_history', models.CharField(choices=[('suspicious', 'Suspicious'), ('legitimate', 'Legitimate')], max_length=20)),
                ('trade_frequency', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
