# Generated by Django 5.1.5 on 2025-02-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='settlement_bank_name',
            new_name='clearing_house_source',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='instrument_ISIN',
            new_name='instrument_CUSIP',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='notional_value',
            new_name='trade_notional_value',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='trade_price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='quantity',
            new_name='trade_quantity',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='instrument_symbol',
        ),
        migrations.AlterField(
            model_name='trade',
            name='settlement_status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
