# Generated by Django 5.1.5 on 2025-02-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_settlement_bank_name_trade_clearing_house_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_date',
            field=models.DateField(),
        ),
    ]
