# Generated by Django 5.1.5 on 2025-02-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_trade_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_quantity',
            field=models.IntegerField(),
        ),
    ]
