# Generated by Django 5.1.5 on 2025-02-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_trade_trade_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
