# Generated by Django 5.1.5 on 2025-02-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_trade_trade_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_quantity',
            field=models.FloatField(),
        ),
    ]
