# Generated by Django 5.1.5 on 2025-02-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_trade_trade_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_or_sell',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4),
        ),
    ]
