# Generated by Django 5.1.5 on 2025-02-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_trade_buy_or_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_quantity',
            field=models.CharField(max_length=20),
        ),
    ]
