# Generated by Django 5.1.5 on 2025-02-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_trade_trade_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_quantity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
